apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: wilpaiz/auth-service:v1
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: MYSQL_SERVICE_BASE_URL
              value: "http://mysql-service:8084"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-jwt-secret
                  key: jwt-secret
            - name: JWT_EXPIRATION
              value: "604800016"