apiVersion: batch/v1
kind: Job
metadata:
  name: image-processing-job
spec:
  template:
    spec:
      containers:
      - name: image-processor
        image: wilpaiz/python-job:v1.1
        imagePullPolicy: Always
        command: ["python", "script.py"]
      restartPolicy: Never
  backoffLimit: 4
